### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _SSL_load_error_strings

### ISSUE THREAD

**Issue by lightfuze** [scttnlsn/dandelion#129] opened 2015-05-26 20:43 UTC
I get the following when trying to run any dandelion command:

`````
dyld: lazy symbol binding failed: Symbol not found: _SSL_load_error_strings
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/rugged-0.22.2/lib/rugged/rugged.bundle
  Expected in: flat namespace

dyld: Symbol not found: _SSL_load_error_strings
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/rugged-0.22.2/lib/rugged/rugged.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
`````
OS X 10.10.3
dandelion 0.4.13

**Comment by scttnlsn** [comment] 2015-05-26 20:45
Not sure if this was a regression.  Could you try v0.4.10 as well?

**Comment by lightfuze** [comment] 2015-05-26 20:52
0.4.10 also installed rugged-0.21.4, but i'm getting the same result

**Comment by TheLonelyGhost** [comment] 2015-05-26 22:31
Hold up, this says you're running rugged v0.22.2, but the manifest for dandelion 0.4.13 requires rugged v0.22.1b1. Perhaps this is a problem with the way rubygems is resolving versions? When you install dandelion 0.4.10, open an IRB session and run the following:

```
require 'dandelion'

puts Rugged::VERSION
```

**Comment by lightfuze** [comment] 2015-05-27 13:15
installing rugged -v0.22.1b1 and uninstalling the other versions did the trick

**Comment by scttnlsn** [comment] 2015-05-27 13:18
@lightfuze So was this an issue specific to your setup or is there an issue with Dandelion?  If there's an issue can you outline the steps I can take to reproduce it?

**Comment by lightfuze** [comment] 2015-05-27 13:25
@scttnlsn I recently did a `````gem update`````. I had been on dandelion -v0.4.6. After that is when I noticed the issue. I think this was probably not a dandelion issue, but possibly due another version of rugged that didn't want to play.

**Comment by scttnlsn** [comment] 2015-05-27 13:40
Okay, thanks.  Re-open this issue if you encounter the problem again.

**Closed by scttnlsn** 2015-05-27 13:40 UTC

**Comment by TheLonelyGhost** [comment] 2015-05-27 14:21
@scttnlsn This actually seems to be a bug with the gemspec definition. Would require further testing to ensure compatibility with rugged v0.22.2. If it is not compatible, the gemspec should have an upper version limit set for the Rugged dependency.

**Comment by scttnlsn** [comment] 2015-05-27 16:13
@TheLonelyGhost Yeah, you're right.  Here's the Rugged issue for this: https://github.com/libgit2/rugged/issues/475

I'll update the Gemspec and push a new version for now.

Thanks!
