### ISSUE TITLE
Error Dandelion status

### ISSUE THREAD

**Issue by kevwaddell** [scttnlsn/dandelion#137] opened 2015-07-09 11:43 UTC
I get the following when I try any of the dandelion commands apart from -h to -v.

    /Users/username/.rvm/gems/ruby-2.2.1@global/gems/dandelion-0.4.14/lib/dandelion/cli.rb:41:in `command_class': undefined method `to_sym' for nil:NilClass (NoMethodError)
    	from /Users/username/.rvm/gems/ruby-2.2.1@global/gems/dandelion-0.4.14/lib/dandelion/cli.rb:67:in `execute!'
    	from /Users/username/.rvm/gems/ruby-2.2.1@global/gems/dandelion-0.4.14/bin/dandelion:8:in `<top (required)>'
    	from /Users/username/.rvm/gems/ruby-2.2.1@global/bin/dandelion:23:in `load'
    	from /Users/username/.rvm/gems/ruby-2.2.1@global/bin/dandelion:23:in `<main>'
    	from /Users/username/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/username/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'

**Comment by scttnlsn** [comment] 2015-07-09 12:28
This sounds like a duplicate of https://github.com/scttnlsn/dandelion/issues/76.  I was never able to reproduce.  Could you provide more info?

**Comment by kevwaddell** [comment] 2015-07-09 13:14
Hi Scott

All working fine now.

Did my first deploy and it worked fine.

Thanks for the response.

Kevin

[cid:0907FFD9-CC12-45D8-A2AA-15C72B699880]



Kevin Waddell
Web Designer/Developer
www.tlwsolicitors.co.uk<http://www.tlwsolicitors.co.uk/>
Office Tel: 0191 293 1500
Mobile: 07515006119
Fax: 0191 293 1501


[cid:97ABF262-1B7F-4656-80E0-BC7657B74B6F]<https://www.facebook.com/tlwsolicitorsuk>[cid:C5BA2A54-DF1A-4529-8DC8-DF46DC32D253]<https://twitter.com/tlwsolicitors>[cid:73655890-7D14-49BB-AF29-C16D570E2717]<https://www.linkedin.com/company/tlw-solicitors>[cid:F93CA4BB-2482-4AD5-9721-4FB62B7F58CF]<https://plus.google.com/+TlwsolicitorsCoUk/>
<https://plus.google.com/+TlwsolicitorsCoUk/>







[cid:image002.gif@01CEB2E0.CE5E7B80]




<https://plus.google.com/+TlwsolicitorsCoUk/>

-----------------------------------------------------------------------------------------------------------

tlw solicitors is a trading name of TLW LLP a limited liability partnership registered in England (Registration OC314139).
TLW LLP are a firm of solicitors authorised and regulated by the Solicitors Regulation Authority.
Full details can be found at <https://plus.google.com/+TlwsolicitorsCoUk/> www.sra.org.uk<http://www.sra.org.uk/>
TLW LLP are registered with The Law Society of England & Wales.

TLW LLP has its registered office at, 9 Hedley Court , Orion Business Park , North Shields, NE29 7ST. VAT registration no. 746973089 A list of members is available for inspection at this address.

TLW LLP is an English limited liability partnership which has “members” and “not” partners. Reference to a partner in our dealings with you is a reference to a member of TLW LLP, or an individual controlling a corporate member of TLW LLP.

Disclaimer: Any views or opinions expressed are those of the sender and do not necessarily reflect the views or opinions of TLW LLP.

Confidentiality: The information contained in this email and any files transmitted with it are confidential and are intended for the addressee only. If you have received this email in error, please notify the originator or telephone 0191 2931500. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose the email or any part of its contents or take any action in reliance on it.

Viruses: TLW LLP will not be liable for any losses as a result of any viruses being passed on as a result of this email. We recommend that you subject this email to your virus checking procedures prior to use.

Monitoring: TLW LLP may monitor email traffic on its system. By replying to this message you give your consent to such monitoring.

Security: This email has been created and sent in the knowledge that it is not a 100% secure communication medium. You are advised to consider this lack of security when sending or receiving emails.





On 9 Jul 2015, at 13:28, Scott Nelson <notifications@github.com<mailto:notifications@github.com>> wrote:


This sounds like a duplicate of #76<https://github.com/scttnlsn/dandelion/issues/76>. I was never able to reproduce. Could you provide more info?

**Closed** 2015-07-09 13:14 UTC

**Comment by scttnlsn** [comment] 2015-07-09 13:23
OK, great.  Could you explain the solution for future reference?
